services:
  db:
    image: postgres:15
    container_name: omnibus-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bd_omnibus
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: omnibus-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@omnibus.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  minio:
    image: minio/minio:latest
    container_name: omnibus-minio
    ports:
      - "9000:9000"   # API do MinIO
      - "9001:9001"   # Interface Web (Console)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  sonarqube:
    image: sonarqube:lts
    container_name: omnibus-sonarqube
    restart: always
    ports:
      - "9002:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  pg_data:
  pgadmin_data:
  minio_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: